ni_mon:
  host: http://141.223.181.149:8383
ni_nfvo:
  host: http://141.223.181.149:8181
instance:                                   # Information of new instance created by a scale-out action
  id: ubuntu                                # SSH ID of new VNF instance
  password: dpnm                        # SSH ID of new VNF instance
image:                                      # Image IDs used by OpenStack
  firewall: 15e16656-0e93-4593-9726-9195ba2babe3
  flowmonitor: a458f634-958a-4182-8d4b-115a7b4c4006
  dpi: 381f99c8-536d-4915-aad7-8fd974fcbabd
  ids: 414aafa2-1380-4499-bbde-f5f8caf75cf5
  proxy: 92e7b3f3-bb91-4980-a20a-0a802f332dd1
  sla_monitor: 10a4457b-7a67-4dd3-9fee-fb8eb42794cd  # Image : 220914_sla_monitor
  nat: 9e129891-e7c4-46f3-b24e-4371b716d359          # HDN : I copied u16.04_x64 image as default
  wano: 9e129891-e7c4-46f3-b24e-4371b716d359         # HDN : I copied u16.04_x64 image as default
flavor:                                     # Flavor ID used by OpenStack
  default: 286a885a-9ebf-4bfc-8652-b4ccd7e8d04d #75626b49-356a-4055-af32-ecbd41b03df8

